name: verify

on: push

jobs:
  verify:
    permissions:
       actions: write
       checks: write
       contents: write
       deployments: write
       issues: write
       packages: write
       pull-requests: write
       repository-projects: write
       security-events: write
       statuses: write
    runs-on: ubuntu-latest 

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v1

    - name: Install dependencies
      run: pip3 install -U online-judge-verify-helper


    - name: Run tests
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        YUKICODER_TOKEN: ${{ secrets.YUKICODER_TOKEN }}
        GH_PAT: ${{ secrets.GH_PAT }}
      run: oj-verify all
